### PR TITLE
Adding example gatekeeper policies

### PR DESCRIPTION
**Pull request by jasonumiker**
I've created a set of OPA Gatekeeper policies that can be applied by default with associated documentation as to what they are, why they were chosen and how to use them. I was attempting to merge these with the existing examples but given that the entire set along with the tests and examples go together it was easier to replace them.

### CODE REVIEW

**Comment by jicowan** [comment]
@jasonumiker I'm not sure we want to replace the existing policies.  What was wrong with the existing policies that you had to replace them?

**Comment by jasonumiker** [comment]
I am replacing them with the example policies that do the same/similar thing from the upstream OPA Gatekeeper Library. I had a whole library put together from that - and documented - that I built with a customer and trying to retrofit it into the existing polices is much more work. This collection of policies I believe represents 'sensible defaults' people can deploy to a cluster as a whole as well rather than the policies they replaced which were meant more as inspiration.

**Comment by jimmyraywv** [comment]
Are ALL the current policies/checks covered/satisfied in the new policies?

**Comment by jasonumiker** [comment]
The intention of this is that it is something that can be deployed as-is without needing to be customised to the organisation. As such:
- I didn't include the restrictions based on labels. I did, however, talk to that in the "What are some other policies you might want to consider?" section and linked them to the library of those sorts of policies in the Gatekeeper examples.
- I didn't include the restrictions based on what registry to pull from. I did, however, talk to that in the "What are some other policies you might want to consider?" section and linked them to the library of those sorts of policies in the Gatekeeper examples.

**Pull request closed without merging**
