### PR TITLE
Networking Japanese docs added

### PR DESCRIPTION
**Pull request by Taiki130**
*Issue #, if available:*

*Description of changes:*

- Japanese docs added (networking)
  -  index, subnets, ip-optimization-strategies, vpc-cni

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nysdin** [comment]
nice!

**Comment by svennam92** [comment]
@Taiki130 thank you for the translation PR. can you please provide a tentative plan for merging the remaining pages to be translated, as well as updating translations when new PRs are made to the content?

**Comment by Taiki130** [comment]
@svennam92 Thank you for the review! Here’s the tentative plan for the remaining translations and future updates:

**1.Remaining Pages Translation:** I’ll focus on completing the translation of the network-related sections within the next two weeks. The other sections don’t have a specific timeline right now, but I’m open to prioritizing any that are more urgent.
**2.Updating Translations for New PRs:** I’ll update the translations as soon as I notice any new PRs affecting the documentation.

Let me know if this works for you or if there are any adjustments needed. Thanks again!

**Comment by svennam92** [comment]
We are now fully migrated to the official AWS docs and translations are included there.

**Pull request closed without merging**
