### PR TITLE
Networking/CoreDNS Monitoring conntrack in EC2

### PR DESCRIPTION
**Pull request by awsvikram**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sheetaljoshi** [comment]
Vikram, could it be possible to enhance this PR to include 

1. bw_in_allowance_exceeded and bw_out_allowance_exceeded
2. pps_allowance_exceeded

The ethtool used within the prometheus exporter appears to already support the scraping of these metrics.

**Comment by sheetaljoshi** [comment]
Vikram, could it be possible to enhance this PR to include 

1. bw_in_allowance_exceeded and bw_out_allowance_exceeded
2. pps_allowance_exceeded

The ethtool used within the prometheus exporter appears to already support the scraping of these metrics.

**Comment by sheetaljoshi** [comment]
Additionally, can we rename the existing networking/CoreDNS/ section networking/monitoring and change the left nav title to "Monitoring for network performance issues". Make the existing content as a subsection.

**Review by jicowan — APPROVED** [review]
LGTM

**Pull request merged**
