### PR TITLE
EKS Best Practice Korean documents added.

### PR DESCRIPTION
**Pull request by Simyung**
Issue #, if available: N/A

Description of changes: 
- EKS BP Korean docs updated.
- mkdocs file updated. (korean nav menu text and additional plugin added <mkdocs-static-i18n==0.53>)
- Korean BP docs add (*.kr.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jicowan** [comment]
Sorry for the delay. Have you tested this? Can you send me a screenshot of the website after these changes are merged? I'd like to see that before I merge this change.

**Comment by Simyung** [comment]
Yes, you can review the website after the merge on the link [here](https://simyung.github.io/aws-eks-best-practices/).

**Comment by jicowan** [comment]
@Simyung the merge failed because the "push contains secrets".

**Comment by Simyung** [comment]
I will close the PR because of secret issue, and create PRs with separate files.

**Pull request closed without merging**
