### PR TITLE
update iframe within markdown

### PR DESCRIPTION
**Pull request by rameshvr**
*Issue #, if available:*

*Description of changes:*
Update video embedding within wiki. Using image link instead of iframe as markdown doesn't support iframe

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jicowan** [comment]
What browser are you using? I can see the iFrame in Chrome.

**Comment by rameshvr** [comment]
I am on Safari Version 16.6 (18615.3.12.11.2)
Below is the screenshot 
image

**Comment by jicowan** [comment]
@rothgar can you have a look at this?

**Comment by rothgar** [comment]
I'm on the same version of safari and the iframes load for me. I checked multiple pages.

What do you see at the top of this page? https://aws.github.io/aws-eks-best-practices/networking/ipv6/

**Comment by rothgar** [comment]
I noticed you sent a screenshot from the github page. The docs don't render in the github view. They're only rendered on the full site running at https://aws.github.io/aws-eks-best-practices/

**Comment by rameshvr** [comment]
Yes I see the video thumbnail with iframe in the website view.

**Pull request closed without merging**
