### PR TITLE
Adding guidance on reliable connection to Kubernetes Control Plane

### PR DESCRIPTION
**Pull request by mekza**
This section gives guidance on reliable connection to K8s control plane

*Description of changes:*

Adding a paragraph on the resiliency section to add guidance on Kubernetes control plane connection

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by svennam92** [comment]
@mekza thank you for the contribution. Can we link to a specific commit in the K8s python client to prevent issues with the link being accurate in the future? Also please include a link to Backoff and Jitter

**Review by svennam92 — CHANGES_REQUESTED** [review]
@mekza thank you for the contribution. Can we link to a specific commit in the K8s python client to prevent issues with the link being accurate in the future? Also please include a link to Backoff and Jitter

**Comment by svennam92** [comment]
@CodiumAI-Agent /improve

**Comment by mekza** [comment]
@svennam92 Thanks for the feedback I incorporated some the suggestions, let me know what you think!

**Review by svennam92 — APPROVED** [review]
LGTM! Thank you for the PR.

**Pull request merged**
